# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

address_aton <- function(x) {
    .Call(`_ipaddress_address_aton`, x)
}

address_ntoa <- function(x) {
    .Call(`_ipaddress_address_ntoa`, x)
}

network_aton <- function(x) {
    .Call(`_ipaddress_network_aton`, x)
}

network_ntoa <- function(x) {
    .Call(`_ipaddress_network_ntoa`, x)
}

