# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wrap_parse_address <- function(x) {
    .Call(`_ipaddress_wrap_parse_address`, x)
}

wrap_print_address <- function(x) {
    .Call(`_ipaddress_wrap_print_address`, x)
}

wrap_encode_bytes <- function(x) {
    .Call(`_ipaddress_wrap_encode_bytes`, x)
}

wrap_decode_bytes <- function(x) {
    .Call(`_ipaddress_wrap_decode_bytes`, x)
}

wrap_encode_integer <- function(x) {
    .Call(`_ipaddress_wrap_encode_integer`, x)
}

wrap_decode_integer <- function(x, is_ipv6) {
    .Call(`_ipaddress_wrap_decode_integer`, x, is_ipv6)
}

wrap_encode_bits <- function(x) {
    .Call(`_ipaddress_wrap_encode_bits`, x)
}

wrap_decode_bits <- function(x) {
    .Call(`_ipaddress_wrap_decode_bits`, x)
}

wrap_encode_hostname <- function(x) {
    .Call(`_ipaddress_wrap_encode_hostname`, x)
}

wrap_decode_hostname <- function(x) {
    .Call(`_ipaddress_wrap_decode_hostname`, x)
}

wrap_parse_network <- function(x, strict) {
    .Call(`_ipaddress_wrap_parse_network`, x, strict)
}

wrap_construct_network_from_address <- function(address, prefix_length, strict) {
    .Call(`_ipaddress_wrap_construct_network_from_address`, address, prefix_length, strict)
}

wrap_print_network <- function(x) {
    .Call(`_ipaddress_wrap_print_network`, x)
}

wrap_parse_interface <- function(x) {
    .Call(`_ipaddress_wrap_parse_interface`, x)
}

wrap_construct_interface_from_address <- function(address, prefix_length) {
    .Call(`_ipaddress_wrap_construct_interface_from_address`, address, prefix_length)
}

wrap_compare_address <- function(x) {
    .Call(`_ipaddress_wrap_compare_address`, x)
}

wrap_network_hosts <- function(network_r, exclude_unusable) {
    .Call(`_ipaddress_wrap_network_hosts`, network_r, exclude_unusable)
}

wrap_sample_network <- function(network_r, size) {
    .Call(`_ipaddress_wrap_sample_network`, network_r, size)
}

wrap_bitwise_not <- function(lhs) {
    .Call(`_ipaddress_wrap_bitwise_not`, lhs)
}

wrap_bitwise_and <- function(lhs, rhs) {
    .Call(`_ipaddress_wrap_bitwise_and`, lhs, rhs)
}

wrap_bitwise_or <- function(lhs, rhs) {
    .Call(`_ipaddress_wrap_bitwise_or`, lhs, rhs)
}

wrap_bitwise_xor <- function(lhs, rhs) {
    .Call(`_ipaddress_wrap_bitwise_xor`, lhs, rhs)
}

wrap_add_integer <- function(lhs, rhs) {
    .Call(`_ipaddress_wrap_add_integer`, lhs, rhs)
}

wrap_netmask <- function(prefix_length, is_ipv6) {
    .Call(`_ipaddress_wrap_netmask`, prefix_length, is_ipv6)
}

wrap_hostmask <- function(prefix_length, is_ipv6) {
    .Call(`_ipaddress_wrap_hostmask`, prefix_length, is_ipv6)
}

wrap_broadcast_address <- function(network_r) {
    .Call(`_ipaddress_wrap_broadcast_address`, network_r)
}

wrap_is_within <- function(address_r, network_r) {
    .Call(`_ipaddress_wrap_is_within`, address_r, network_r)
}

wrap_is_within_any <- function(address_r, network_r) {
    .Call(`_ipaddress_wrap_is_within_any`, address_r, network_r)
}

wrap_is_multicast <- function(x) {
    .Call(`_ipaddress_wrap_is_multicast`, x)
}

wrap_is_unspecified <- function(x) {
    .Call(`_ipaddress_wrap_is_unspecified`, x)
}

wrap_is_loopback <- function(x) {
    .Call(`_ipaddress_wrap_is_loopback`, x)
}

wrap_is_link_local <- function(x) {
    .Call(`_ipaddress_wrap_is_link_local`, x)
}

wrap_is_ipv4_mapped <- function(x) {
    .Call(`_ipaddress_wrap_is_ipv4_mapped`, x)
}

wrap_extract_ipv4_mapped <- function(address_r) {
    .Call(`_ipaddress_wrap_extract_ipv4_mapped`, address_r)
}

wrap_is_6to4 <- function(x) {
    .Call(`_ipaddress_wrap_is_6to4`, x)
}

wrap_extract_6to4 <- function(address_r) {
    .Call(`_ipaddress_wrap_extract_6to4`, address_r)
}

wrap_is_teredo <- function(x) {
    .Call(`_ipaddress_wrap_is_teredo`, x)
}

wrap_extract_teredo_server <- function(address_r) {
    .Call(`_ipaddress_wrap_extract_teredo_server`, address_r)
}

wrap_extract_teredo_client <- function(address_r) {
    .Call(`_ipaddress_wrap_extract_teredo_client`, address_r)
}

